# Application secrets for crystaldocs
resource "kubernetes_secret" "crystaldocs_secrets" {
  metadata {
    name      = "crystaldocs-secrets"
    namespace = kubernetes_namespace.crystaldocs.metadata[0].name
  }

  data = {
    # CNPG creates a read-write service: <cluster-name>-rw
    # CNPG creates an app secret: <cluster-name>-app with username/password
    # We use a data source to get the actual password from the CNPG-generated secret
    # Format: postgresql://app:password@service:5432/database
    database_url = "postgresql://app:${data.kubernetes_secret.crystaldocs_postgres_app.data["password"]}@crystaldocs-postgres-rw:5432/crystaldocs_production"

    # Secure SECRET_KEY_BASE generated by Terraform random provider
    secret_key_base = random_password.crystaldocs_secret_key_base.result
  }

  type = "Opaque"
}
