# Application secrets for crystaldocs
resource "kubernetes_secret" "crystaldocs_secrets" {
  metadata {
    name      = "crystaldocs-secrets"
    namespace = kubernetes_namespace.crystaldocs.metadata[0].name
  }

  data = {
    # CNPG creates a read-write service: <cluster-name>-rw
    # CNPG creates an app secret: <cluster-name>-app with username/password
    # We use a data source to get both username and password from the CNPG-generated secret
    # Format: postgresql://username:password@service:5432/database
    database_url = "postgresql://${data.kubernetes_secret.crystaldocs_postgres_app.data["username"]}:${data.kubernetes_secret.crystaldocs_postgres_app.data["password"]}@crystaldocs-postgres-rw:5432/crystaldocs_production"

    # MinIO credentials from operator-generated secret
    minio_endpoint    = "shared-storage-hl.infrastructure.svc.cluster.local:9000"
    minio_access_key  = data.kubernetes_secret.minio_user.data["CONSOLE_ACCESS_KEY"]
    minio_secret_key  = data.kubernetes_secret.minio_user.data["CONSOLE_SECRET_KEY"]
    minio_region      = "us-east-1"
    minio_use_ssl     = "false"

    # Secure SECRET_KEY_BASE generated by Terraform random provider
    secret_key_base = random_password.crystaldocs_secret_key_base.result
  }

  type = "Opaque"
}
