#!/bin/bash
# Simple test script to verify environment variables are passed correctly

echo "🔍 Environment Variable Check"
echo "============================"
echo ""
echo "Critical Variables:"
echo "  ANTHROPIC_API_KEY: $(if [ -n "$ANTHROPIC_API_KEY" ]; then echo "✅ Set (${#ANTHROPIC_API_KEY} chars)"; else echo "❌ Not set"; fi)"
echo "  GITHUB_TOKEN: $(if [ -n "$GITHUB_TOKEN" ]; then echo "✅ Set (${#GITHUB_TOKEN} chars)"; else echo "❌ Not set"; fi)"
echo ""
echo "Git Configuration:"
echo "  GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME:-Not set}"
echo "  GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL:-Not set}"
echo "  GIT_COMMITTER_NAME: ${GIT_COMMITTER_NAME:-Not set}"
echo "  GIT_COMMITTER_EMAIL: ${GIT_COMMITTER_EMAIL:-Not set}"
echo ""
echo "Envbuilder Variables:"
echo "  ENVBUILDER_GIT_URL: ${ENVBUILDER_GIT_URL:-Not set}"
echo "  ENVBUILDER_GIT_BRANCH: ${ENVBUILDER_GIT_BRANCH:-Not set}"
echo "  ENVBUILDER_DEVCONTAINER_DIR: ${ENVBUILDER_DEVCONTAINER_DIR:-Not set}"
echo "  ENVBUILDER_INIT_SCRIPT: ${ENVBUILDER_INIT_SCRIPT:-Not set}"
echo ""
echo "Other:"
echo "  WORKSPACE: ${WORKSPACE:-Not set}"
echo "  PWD: $PWD"
echo "  USER: $USER"
echo ""