# Application secrets for crystalgigs
resource "kubernetes_secret" "crystalgigs_secrets" {
  metadata {
    name      = "crystalgigs-secrets"
    namespace = kubernetes_namespace.crystalgigs.metadata[0].name
  }

  data = {
    # CNPG creates a read-write service: <cluster-name>-rw
    # CNPG creates an app secret: <cluster-name>-app with username/password
    # We use a data source to get both username and password from the CNPG-generated secret
    # Format: postgresql://username:password@service:5432/database
    database_url = "postgresql://${data.kubernetes_secret.crystalgigs_postgres_app.data["username"]}:${data.kubernetes_secret.crystalgigs_postgres_app.data["password"]}@crystalgigs-postgres-rw:5432/crystalgigs_production"

    # Secure SECRET_KEY_BASE generated by Terraform random provider
    secret_key_base = random_password.crystalgigs_secret_key_base.result

    # Resend API key for email functionality
    resend_key = var.resend_key

    # Stripe API keys for payment processing
    stripe_secret_key      = var.stripe_secret_key
    stripe_publishable_key = var.stripe_publishable_key
  }

  type = "Opaque"

  lifecycle {
    # Force replacement when CNPG secrets change
    # This ensures database credentials are always current
    replace_triggered_by = [
      data.kubernetes_secret.crystalgigs_postgres_app.id
    ]
  }
}
