# Application secrets for crystalbits
resource "kubernetes_secret" "crystalbits_secrets" {
  metadata {
    name      = "crystalbits-secrets"
    namespace = kubernetes_namespace.crystalbits.metadata[0].name
  }

  data = {
    # CNPG creates a read-write service: <cluster-name>-rw
    # CNPG creates an app secret: <cluster-name>-app with username/password
    # CNPG creates an app secret: <cluster-name>-app with password ONLY
    # Username matches bootstrap.initdb.owner from the cluster manifest ("crystalbits")
    # We use a data source to get the password from the CNPG-generated secret
    # Format: postgresql://username:password@service:5432/database
    database_url = "postgresql://crystalbits:${data.kubernetes_secret.crystalbits_postgres_app.data["password"]}@crystalbits-postgres-rw:5432/crystalbits_production"

    # Secure SECRET_KEY_BASE generated by Terraform random provider
    secret_key_base = random_password.crystalbits_secret_key_base.result

    # Resend API key for email functionality
    resend_key = var.resend_key
  }

  type = "Opaque"

  lifecycle {
    # Force replacement when CNPG secrets change
    # This ensures database credentials are always current
    replace_triggered_by = [
      data.kubernetes_secret.crystalbits_postgres_app.id
    ]
  }
}
