# Application secrets for crystalshards
resource "kubernetes_secret" "crystalshards_secrets" {
  metadata {
    name      = "crystalshards-secrets"
    namespace = kubernetes_namespace.crystalshards.metadata[0].name
  }

  data = {
    # CNPG creates a read-write service: <cluster-name>-rw
    # CNPG creates an app secret: <cluster-name>-app with password ONLY
    # Username matches bootstrap.initdb.owner from the cluster manifest ("crystalshards")
    # Format: postgresql://username:password@service:5432/database
    database_url = "postgresql://crystalshards:${data.kubernetes_secret.crystalshards_postgres_app.data["password"]}@crystalshards-postgres-rw:5432/crystalshards_production"

    # Redis URL for Mosquito workers - shared Redis in infrastructure namespace
    redis_url = "redis://shared-redis.infrastructure.svc.cluster.local:6379/0"

    # MinIO credentials from operator-generated secret
    minio_endpoint   = "shared-storage-hl.infrastructure.svc.cluster.local:9000"
    minio_access_key = data.kubernetes_secret.minio_user.data["CONSOLE_ACCESS_KEY"]
    minio_secret_key = data.kubernetes_secret.minio_user.data["CONSOLE_SECRET_KEY"]
    minio_region     = "us-east-1"
    minio_use_ssl    = "false"

    # Secure SECRET_KEY_BASE generated by Terraform random provider
    secret_key_base = random_password.crystalshards_secret_key_base.result
  }

  type = "Opaque"

  lifecycle {
    # Force replacement when CNPG or MinIO secrets change
    # This ensures database credentials are always current
    replace_triggered_by = [
      data.kubernetes_secret.crystalshards_postgres_app.id,
      data.kubernetes_secret.minio_user.id
    ]
  }
}
